# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BJOC-nl
author: Dutch version vakvereniging i&i, Felienne Hermans, Alexander Serebrenik,  Wendy d’Hollosy, Renske Weeda, Ramon Moorlag. English version UC Berkeley, Dan Garcia, Brian Harvey, Tiffany Barnes, Michael Ball, Lauren Mock
email: bestuur@ieni.org
description: >
  Beauty and Joy of Computing (BJOC-NL) is een lesmethode ontwikkeld door Berkeley om middelbare scholieren op een creatieve manier kennis te laten maken met programmeren en informatica in brede zin. In de VS zijn er grote successen mee geboekt, bijv. in het aantrekken van meer vrouwelijke studenten op Berkeley.
keywords: >
  informatica, digitale geletterdheid, computer science, Snap!, Snap,
  programming, computing, BJC, computer science, cs10, bjcx, bjc4nyc
baseurl: ""
# NOTE: This URL is needed for Github pages. It will get overriden
# in the build scripts.
url: "https://www.ramonmoorlag.nl/beautyjoy.github.io"
permalink: pretty

# This is used for displaying a warning on sites that aren't the
# production site.
production_url: https://ramonmoorlag.nl/
twitter_username:   ieni
# facebook_username:  cspbjc
instagram_username: codeweek
# flipboard_link:     https://bjc.link/computingnews

# Misc shared data.
# nyc_pd_page: https://cs4all.nyc/programs/
# pd_interest_url: https://bjc.link/pdinterest18

# jekyll SEO tag attributes:
twitter:
    card: base
    username: cspbjc
logo: /assets/img/bjc.png
lang: en_US
social:
    name: BJOC-NL
    links:
        - https://twitter.com/ieni
#        - https://www.facebook.com/cspbjc
#        - https://github.com/beautyjoy
#        - https://instagram.com/cspbjc
google_site_verification:

# These are specifically whitelisted by Github
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
include:
  - .htaccess
exclude:
  - redirects.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor # created when the site is built on CircleCI
  - package.json
